---

dictionaryDefinitions:
  - name: Spellcheck Overrides
    path: ./cspell_dictionary.txt
    addWords: true

dictionaries:
  - overrides

words:
  - addrs
  - CDPATH
  - cdrom
  - checkwinsize
  - cidrcontains
  - cloudinit
  - COLORTERM
  - Colour
  - Containerfile
  - diffutils
  - dmacvicar
  - domifaddr
  - ensurepip
  - gecos
  - gruntfuggly
  - HEALTHCHECK
  - histappend
  - HISTCONTROL
  - HISTFILESIZE
  - HISTSIZE
  - HISTTIMEFORMAT
  - hwaddr
  - iface
  - ignoredups
  - ignorespace
  - iputils
  - libatomic
  - myuser
  - nodocs
  - procps
  - qcow
  - SCAP
  - setopt
  - shopt
  - snapp
  - tflint
  - tfupdate
  - tfvars
  - truecolor
  - userns
  - vcpu
  - vhost
  - virbr
  - virsh
  - virt
  - virtio

ignorePaths:
  - "**/.github/CODEOWNERS"
  - "**/.github/settings.yml"
  - "**/.gitignore"
  - "**/.pre-commit-config.yaml"
  - "**/cspell.config.yml"
