#!/usr/bin/env bash

# Source global definitions
if [ -f /etc/bashrc ]; then
  source /etc/bashrc
fi

# Add $HOME to cd path
export CDPATH=".:${HOME}:/workspaces"

# Add asdf shims to path
export PATH="${HOME}/.asdf/shims:${HOME}/.local/bin:${PATH}"

# Short-List
alias ls='ls --color=auto'

# Long-List
alias ll='ls -l --color=auto'

# append to the history file, don't overwrite it
shopt -s histappend

# update the values of LINES and COLUMNS after each command
shopt -s checkwinsize

# Append to history prior to issuing each prompt
export PROMPT_COMMAND='history -a'

# Set prompt
export PS1='[\W]🅣  '
